//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIResourceSchemaRef) DeepCopyInto(out *APIResourceSchemaRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIResourceSchemaRef.
func (in *APIResourceSchemaRef) DeepCopy() *APIResourceSchemaRef {
	if in == nil {
		return nil
	}
	out := new(APIResourceSchemaRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchConfig) DeepCopyInto(out *SearchConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchConfig.
func (in *SearchConfig) DeepCopy() *SearchConfig {
	if in == nil {
		return nil
	}
	out := new(SearchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchConfigList) DeepCopyInto(out *SearchConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchConfigList.
func (in *SearchConfigList) DeepCopy() *SearchConfigList {
	if in == nil {
		return nil
	}
	out := new(SearchConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchConfigSpec) DeepCopyInto(out *SearchConfigSpec) {
	*out = *in
	out.APIResourceSchemaRef = in.APIResourceSchemaRef
	if in.ExcludedFields != nil {
		in, out := &in.ExcludedFields, &out.ExcludedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SemanticFields != nil {
		in, out := &in.SemanticFields, &out.SemanticFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExactFields != nil {
		in, out := &in.ExactFields, &out.ExactFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchConfigSpec.
func (in *SearchConfigSpec) DeepCopy() *SearchConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SearchConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchConfigStatus) DeepCopyInto(out *SearchConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchConfigStatus.
func (in *SearchConfigStatus) DeepCopy() *SearchConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SearchConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndex) DeepCopyInto(out *SearchIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndex.
func (in *SearchIndex) DeepCopy() *SearchIndex {
	if in == nil {
		return nil
	}
	out := new(SearchIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndexList) DeepCopyInto(out *SearchIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndexList.
func (in *SearchIndexList) DeepCopy() *SearchIndexList {
	if in == nil {
		return nil
	}
	out := new(SearchIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndexSpec) DeepCopyInto(out *SearchIndexSpec) {
	*out = *in
	if in.SemanticFields != nil {
		in, out := &in.SemanticFields, &out.SemanticFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FilterableFields != nil {
		in, out := &in.FilterableFields, &out.FilterableFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultFields != nil {
		in, out := &in.DefaultFields, &out.DefaultFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndexSpec.
func (in *SearchIndexSpec) DeepCopy() *SearchIndexSpec {
	if in == nil {
		return nil
	}
	out := new(SearchIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchIndexStatus) DeepCopyInto(out *SearchIndexStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchIndexStatus.
func (in *SearchIndexStatus) DeepCopy() *SearchIndexStatus {
	if in == nil {
		return nil
	}
	out := new(SearchIndexStatus)
	in.DeepCopyInto(out)
	return out
}
