apiVersion: core.platform-mesh.io/v1alpha1
kind: SearchIndex
metadata:
  name: testindex5
spec:
  indexPrefix: "orgs"
  trackedResources: []
  numberOfShards: 1
  numberOfReplicas: 0
  organizationClusterID: "xxztm0mcc667heq3"
  